apiVersion: v1
kind: Secret
metadata:
  name: franchise-backend-secret
type: Opaque
data:
 basicAuthUser: ZnJhbmNoaXNlCg==
 basicAuthKey: REFGODdEU0ZEU0ZEU0E5OEZTQURLSkUzMjRLSkwzMkhGRDdGRFNGQjI0MzQzSjQ5RFNGCg==
 MONGO_URL: bW9uZ29kYitzcnY6Ly9BZEVhcm5zOnBpeGFsaXZlQHBpeGFsaXZlLWFkZWFybnMua21tdWF4bC5tb25nb2RiLm5ldC9GcmFuY2g/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5Cg==

